### ISSUE TITLE
Adding support for jQuery :eq(), :lt(), :gt(), :even, :odd

### ISSUE THREAD

**Issue by SamiSaves** [niklas-e/enhanced-js#1]
Is it possible to add support for these jQuery functions as it would make it easier to migrate from jQuery to enhanced-js? The difference between :nth-child and :eq is really minor but might be needed in some cases.

Article from stackoverflow describing the difference: https://stackoverflow.com/questions/15015971/is-there-a-standard-css-selector-similar-to-eq-in-jquery

**Comment by niklas-e** [comment]
I think these can be done quite nicely with a mix of plain selectors and basic JS.
```javascipt
// :eq()
body div:eq(4)
e('body div')[4]

// :lt()
body div:lt(4)
e('body div').slice(0,4)

// :gt()
body div:gt(2)
e('body div').slice(2)

// :even, :odd
e('body div').filter((_, i) => i % 2 == 0)
```
Though it might be worth it to have these directly in the library. Especially because it could also return them as "enhanced arrays" which helps with chaining.

**Comment by niklas-e** [comment]
Not feasible to add as a feature, because all of the use cases can be implemented with plain selectors and JS.
