### ISSUE TITLE
Possibility to add inline styles to elements with an object

### ISSUE THREAD

**Issue by SamiSaves** [niklas-e/enhanced-js#2]
Would it be possible to add a new functionality to add styles to elements with an object?

Example:

```javascript
e.create({ tag: div, style: { background: '#000' }})
// OR
e('div').style = { background: '#000' }
```
Would result to:

```html
<div style="background: #000;"></div>
```

**Comment by niklas-e** [comment]
That's a good idea. Though usually there shouldn't be that much inline styles. However, I think it would be better for readability even if there's only couple of style definitions. I could do an implementation for this in near future... or if you want to do it, make a pull request :)

**Comment by niklas-e** [comment]
@SamiEklund, I added support for setting inline styles. Styles can be set as strings or objects.

Object:
```
var el = e.create({ tag: 'div', style: { background: '#000', width: '100px', height: '100px', position: 'absolute', top: 0, left: 0 }})
document.body.appendChild(el)
```
or
```
e('div').setStyles({ background: 'red', fontSize: '30px' })
```

String:
```
var el = e.create({ tag: 'div', style: 'background: #000; width: 100px; height: 100px; position: absolute; top: 0; left: 0;' })
document.body.appendChild(el)
```
or
```
e('div').setStyles('background: red; fontSize: 30px;')
```

I'll publish the new version to npm later today.
