### ISSUE TITLE
Inconsistent selector results when element is not found

### ISSUE THREAD

**Issue by JuhaHonkaranta** [niklas-e/enhanced-js#3]
If an element is not found the return depends on if an id selector was used or not:
`e('.notFound') => undefined`
`e('#notFound') => null`

Would be nice if it always returned undefined if the element was not found.

**Comment by niklas-e** [comment]
Selectors return an array always, but it's true that the id selector returns null in the first index.
![image](https://user-images.githubusercontent.com/8472329/55055492-c8143100-506b-11e9-90c8-1e78bd0fd6a2.png)

I'll normalize the results to return an empty array if no elements were found.

**Comment by niklas-e** [comment]
Fixed in b0cc50b908e7f6a6ecbb6e12ea6314f049b83609
